version: '3.8'
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
            target: development
        depends_on:
            - mariadb
        environment:
            # localhost
            DATABASE_URL: 'mariadb'
            NODE_ENV: development
            PORT: 3000
        command: npm run start:debug
        ports:
            - "4000:8080"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    mariadb:
        image: mariadb:latest
        ports:
            - "3000:3000"
            - "9229:9229"
        environment:
            MYSQL_DATABASE: "alachiq"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "MyNewPass"
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            - PMA_ARBITRARY=1
